model:
  input_dim: 10
  hidden_dim: 50
  output_dim: 1

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100

data:
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"